train_file: ["./Data/train_part.json"]
val_file: ["./Data/test_part.json"]
bert_config: './bert-chinese/config.json'

image_res: 256
vision_width: 768
embed_dim: 256
batch_size_train: 4
batch_size_val: 4
temp: 0.07
queue_size: 65536
momentum: 0.995
alpha: 0.4
max_words: 50
label_smoothing: 0.0
margin: 0.5

loss_MAC_wgt: 0.1
loss_BIC2ti_wgt: 1
loss_TMG_wgt: 1
loss_MLC_wgt: 1
loss_bbox_wgt: 0.1
loss_giou_wgt: 0.1
loss_con_wgt: 1

optimizer: {opt: adamW, lr: 2e-5, lr_img: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 60,  min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-6, warmup_epochs: 10, cooldown_epochs: 0}








